//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HeadacheModel", "DoctorAccountPatBasicInfor", "DoctorAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HeadacheCDSSWeb.Models.DoctorAccount), "PatBasicInfor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HeadacheCDSSWeb.Models.PatBasicInfor), true)]
[assembly: EdmRelationshipAttribute("HeadacheModel", "PatBasicInforVisitRecord", "PatBasicInfor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(HeadacheCDSSWeb.Models.PatBasicInfor), "VisitRecord", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(HeadacheCDSSWeb.Models.VisitRecord), true)]

#endregion

namespace HeadacheCDSSWeb.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HeadacheModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HeadacheModelContainer object using the connection string found in the 'HeadacheModelContainer' section of the application configuration file.
        /// </summary>
        public HeadacheModelContainer() : base("name=HeadacheModelContainer", "HeadacheModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HeadacheModelContainer object.
        /// </summary>
        public HeadacheModelContainer(string connectionString) : base(connectionString, "HeadacheModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HeadacheModelContainer object.
        /// </summary>
        public HeadacheModelContainer(EntityConnection connection) : base(connection, "HeadacheModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DoctorAccount> DoctorAccountSet
        {
            get
            {
                if ((_DoctorAccountSet == null))
                {
                    _DoctorAccountSet = base.CreateObjectSet<DoctorAccount>("DoctorAccountSet");
                }
                return _DoctorAccountSet;
            }
        }
        private ObjectSet<DoctorAccount> _DoctorAccountSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PatBasicInfor> PatBasicInforSet
        {
            get
            {
                if ((_PatBasicInforSet == null))
                {
                    _PatBasicInforSet = base.CreateObjectSet<PatBasicInfor>("PatBasicInforSet");
                }
                return _PatBasicInforSet;
            }
        }
        private ObjectSet<PatBasicInfor> _PatBasicInforSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VisitRecord> VisitRecordSet
        {
            get
            {
                if ((_VisitRecordSet == null))
                {
                    _VisitRecordSet = base.CreateObjectSet<VisitRecord>("VisitRecordSet");
                }
                return _VisitRecordSet;
            }
        }
        private ObjectSet<VisitRecord> _VisitRecordSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DoctorAccountSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoctorAccountSet(DoctorAccount doctorAccount)
        {
            base.AddObject("DoctorAccountSet", doctorAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PatBasicInforSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatBasicInforSet(PatBasicInfor patBasicInfor)
        {
            base.AddObject("PatBasicInforSet", patBasicInfor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VisitRecordSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVisitRecordSet(VisitRecord visitRecord)
        {
            base.AddObject("VisitRecordSet", visitRecord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HeadacheModel", Name="DoctorAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DoctorAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DoctorAccount object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="passWord">Initial value of the PassWord property.</param>
        /// <param name="hospital">Initial value of the Hospital property.</param>
        public static DoctorAccount CreateDoctorAccount(global::System.Int32 id, global::System.String userName, global::System.String passWord, global::System.String hospital)
        {
            DoctorAccount doctorAccount = new DoctorAccount();
            doctorAccount.Id = id;
            doctorAccount.UserName = userName;
            doctorAccount.PassWord = passWord;
            doctorAccount.Hospital = hospital;
            return doctorAccount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Hospital
        {
            get
            {
                return _Hospital;
            }
            set
            {
                OnHospitalChanging(value);
                ReportPropertyChanging("Hospital");
                _Hospital = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hospital");
                OnHospitalChanged();
            }
        }
        private global::System.String _Hospital;
        partial void OnHospitalChanging(global::System.String value);
        partial void OnHospitalChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HeadacheModel", "DoctorAccountPatBasicInfor", "PatBasicInfor")]
        public EntityCollection<PatBasicInfor> PatBasicInfor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PatBasicInfor>("HeadacheModel.DoctorAccountPatBasicInfor", "PatBasicInfor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PatBasicInfor>("HeadacheModel.DoctorAccountPatBasicInfor", "PatBasicInfor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HeadacheModel", Name="PatBasicInfor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PatBasicInfor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PatBasicInfor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sex">Initial value of the Sex property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="doctorAccountId">Initial value of the DoctorAccountId property.</param>
        public static PatBasicInfor CreatePatBasicInfor(global::System.String id, global::System.String name, global::System.String sex, global::System.String age, global::System.String phone, global::System.String address, global::System.Int32 doctorAccountId)
        {
            PatBasicInfor patBasicInfor = new PatBasicInfor();
            patBasicInfor.Id = id;
            patBasicInfor.Name = name;
            patBasicInfor.Sex = sex;
            patBasicInfor.Age = age;
            patBasicInfor.Phone = phone;
            patBasicInfor.Address = address;
            patBasicInfor.DoctorAccountId = doctorAccountId;
            return patBasicInfor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.String _Age;
        partial void OnAgeChanging(global::System.String value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Education
        {
            get
            {
                return _Education;
            }
            set
            {
                OnEducationChanging(value);
                ReportPropertyChanging("Education");
                _Education = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Education");
                OnEducationChanged();
            }
        }
        private global::System.String _Education;
        partial void OnEducationChanging(global::System.String value);
        partial void OnEducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.String _Job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Identity
        {
            get
            {
                return _Identity;
            }
            set
            {
                OnIdentityChanging(value);
                ReportPropertyChanging("Identity");
                _Identity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Identity");
                OnIdentityChanged();
            }
        }
        private global::System.String _Identity;
        partial void OnIdentityChanging(global::System.String value);
        partial void OnIdentityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChiefDoctor
        {
            get
            {
                return _ChiefDoctor;
            }
            set
            {
                OnChiefDoctorChanging(value);
                ReportPropertyChanging("ChiefDoctor");
                _ChiefDoctor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChiefDoctor");
                OnChiefDoctorChanged();
            }
        }
        private global::System.String _ChiefDoctor;
        partial void OnChiefDoctorChanging(global::System.String value);
        partial void OnChiefDoctorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DoctorAccountId
        {
            get
            {
                return _DoctorAccountId;
            }
            set
            {
                OnDoctorAccountIdChanging(value);
                ReportPropertyChanging("DoctorAccountId");
                _DoctorAccountId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoctorAccountId");
                OnDoctorAccountIdChanged();
            }
        }
        private global::System.Int32 _DoctorAccountId;
        partial void OnDoctorAccountIdChanging(global::System.Int32 value);
        partial void OnDoctorAccountIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HeadacheModel", "DoctorAccountPatBasicInfor", "DoctorAccount")]
        public DoctorAccount DoctorAccount
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DoctorAccount>("HeadacheModel.DoctorAccountPatBasicInfor", "DoctorAccount").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DoctorAccount>("HeadacheModel.DoctorAccountPatBasicInfor", "DoctorAccount").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DoctorAccount> DoctorAccountReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DoctorAccount>("HeadacheModel.DoctorAccountPatBasicInfor", "DoctorAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DoctorAccount>("HeadacheModel.DoctorAccountPatBasicInfor", "DoctorAccount", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HeadacheModel", "PatBasicInforVisitRecord", "VisitRecord")]
        public EntityCollection<VisitRecord> VisitRecord
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VisitRecord>("HeadacheModel.PatBasicInforVisitRecord", "VisitRecord");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VisitRecord>("HeadacheModel.PatBasicInforVisitRecord", "VisitRecord", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HeadacheModel", Name="VisitRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VisitRecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisitRecord object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="outpatientID">Initial value of the OutpatientID property.</param>
        /// <param name="diagnosisResult">Initial value of the DiagnosisResult property.</param>
        /// <param name="cDSSDiagnosis">Initial value of the CDSSDiagnosis property.</param>
        /// <param name="chiefComplaint">Initial value of the ChiefComplaint property.</param>
        /// <param name="visitDate">Initial value of the VisitDate property.</param>
        /// <param name="patBasicInforId">Initial value of the PatBasicInforId property.</param>
        public static VisitRecord CreateVisitRecord(global::System.Int32 id, global::System.String outpatientID, global::System.String diagnosisResult, global::System.String cDSSDiagnosis, global::System.String chiefComplaint, global::System.DateTime visitDate, global::System.String patBasicInforId)
        {
            VisitRecord visitRecord = new VisitRecord();
            visitRecord.Id = id;
            visitRecord.OutpatientID = outpatientID;
            visitRecord.DiagnosisResult = diagnosisResult;
            visitRecord.CDSSDiagnosis = cDSSDiagnosis;
            visitRecord.ChiefComplaint = chiefComplaint;
            visitRecord.VisitDate = visitDate;
            visitRecord.PatBasicInforId = patBasicInforId;
            return visitRecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OutpatientID
        {
            get
            {
                return _OutpatientID;
            }
            set
            {
                OnOutpatientIDChanging(value);
                ReportPropertyChanging("OutpatientID");
                _OutpatientID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OutpatientID");
                OnOutpatientIDChanged();
            }
        }
        private global::System.String _OutpatientID;
        partial void OnOutpatientIDChanging(global::System.String value);
        partial void OnOutpatientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DiagnosisResult
        {
            get
            {
                return _DiagnosisResult;
            }
            set
            {
                OnDiagnosisResultChanging(value);
                ReportPropertyChanging("DiagnosisResult");
                _DiagnosisResult = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DiagnosisResult");
                OnDiagnosisResultChanged();
            }
        }
        private global::System.String _DiagnosisResult;
        partial void OnDiagnosisResultChanging(global::System.String value);
        partial void OnDiagnosisResultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CDSSDiagnosis
        {
            get
            {
                return _CDSSDiagnosis;
            }
            set
            {
                OnCDSSDiagnosisChanging(value);
                ReportPropertyChanging("CDSSDiagnosis");
                _CDSSDiagnosis = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CDSSDiagnosis");
                OnCDSSDiagnosisChanged();
            }
        }
        private global::System.String _CDSSDiagnosis;
        partial void OnCDSSDiagnosisChanging(global::System.String value);
        partial void OnCDSSDiagnosisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChiefComplaint
        {
            get
            {
                return _ChiefComplaint;
            }
            set
            {
                OnChiefComplaintChanging(value);
                ReportPropertyChanging("ChiefComplaint");
                _ChiefComplaint = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChiefComplaint");
                OnChiefComplaintChanged();
            }
        }
        private global::System.String _ChiefComplaint;
        partial void OnChiefComplaintChanging(global::System.String value);
        partial void OnChiefComplaintChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime VisitDate
        {
            get
            {
                return _VisitDate;
            }
            set
            {
                OnVisitDateChanging(value);
                ReportPropertyChanging("VisitDate");
                _VisitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisitDate");
                OnVisitDateChanged();
            }
        }
        private global::System.DateTime _VisitDate;
        partial void OnVisitDateChanging(global::System.DateTime value);
        partial void OnVisitDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PatBasicInforId
        {
            get
            {
                return _PatBasicInforId;
            }
            set
            {
                OnPatBasicInforIdChanging(value);
                ReportPropertyChanging("PatBasicInforId");
                _PatBasicInforId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PatBasicInforId");
                OnPatBasicInforIdChanged();
            }
        }
        private global::System.String _PatBasicInforId;
        partial void OnPatBasicInforIdChanging(global::System.String value);
        partial void OnPatBasicInforIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HeadacheModel", "PatBasicInforVisitRecord", "PatBasicInfor")]
        public PatBasicInfor PatBasicInfor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatBasicInfor>("HeadacheModel.PatBasicInforVisitRecord", "PatBasicInfor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatBasicInfor>("HeadacheModel.PatBasicInforVisitRecord", "PatBasicInfor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PatBasicInfor> PatBasicInforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PatBasicInfor>("HeadacheModel.PatBasicInforVisitRecord", "PatBasicInfor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PatBasicInfor>("HeadacheModel.PatBasicInforVisitRecord", "PatBasicInfor", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
