//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class Prescription
    {
        public Prescription()
        {
            this.MecicationAdvice = new HashSet<MecicationAdvice>();
        }
    
        public int Id { get; set; }
        public string DotorAdvice { get; set; }
    
        public virtual VisitRecord VisitRecord { get; set; }
        public virtual ICollection<MecicationAdvice> MecicationAdvice { get; set; }
    }
    
}
