//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class RelateInfor
    {
        public RelateInfor()
        {
            this.HeadacheFamilyMember = new HashSet<HeadacheFamilyMember>();
            this.OtherFamilyDisease = new HashSet<OtherFamilyDisease>();
        }
    
        public int Id { get; set; }
        public string SimilarFamily { get; set; }
    
        public virtual ICollection<HeadacheFamilyMember> HeadacheFamilyMember { get; set; }
        public virtual ICollection<OtherFamilyDisease> OtherFamilyDisease { get; set; }
        public virtual Lifestyle Lifestyle { get; set; }
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
