//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HeadacheCDSSWeb.Models
{
    public partial class VisitRecord
    {
        public VisitRecord()
        {
            this.CDSSDiagnosis = new HashSet<CDSSDiagnosis>();
            this.DiagnosisResult = new HashSet<DiagnosisResult>();
        }
    
        public int Id { get; set; }
        public string OutpatientID { get; set; }
        public string ChiefComplaint { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string PatBasicInforId { get; set; }
    
        public virtual ICollection<CDSSDiagnosis> CDSSDiagnosis { get; set; }
        public virtual ICollection<DiagnosisResult> DiagnosisResult { get; set; }
        public virtual HeadachaOverView HeadachaOverView { get; set; }
        public virtual MedicalHistory MedicalHistory { get; set; }
        public virtual Prescription Prescription { get; set; }
        public virtual PatBasicInfor PatBasicInfor { get; set; }
    }
    
}
